version: '3'

services:
  mongodb:
    image: mongo:4.4.1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    command: npm run start
    working_dir: /shopy-app
    volumes:
      - .:/shopy-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
